export const GOODS_LOAD_IN_PROGRESS = "GOODS_LOAD_IN_PROGRESS";
export const GOODS_LOAD_FAIL = "GOODS_LOAD_FAIL";
export const ADD_GOODS = "ADD_GOODS";

export const BASKET_LOAD_IN_PROGRESS = "BASKET_LOAD_IN_PROGRESS";
export const BASKET_LOAD_FAIL = "BASKET_LOAD_FAIL";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";